[build]
builder = "railpack"

[build.args]
RECORDBOT_PRICE_2H = ""
RECORDBOT_PRICE_5H = ""
RECORDBOT_PRICE_20H = ""
RECORDBOT_CHANNEL_ID = ""

build]
builder = "dockerfile"

[deploy]
restartPolicyType = "always"
restartPolicyMaxRetries = 5